### ISSUE TITLE
Error During starting of app

### ISSUE THREAD

**Issue by porwal-rahul** [creativetimofficial/argon-design-system#101]
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:120:11)
    at Object.join (path.js:1039:7)
    at noopServiceWorkerMiddleware (/home/rahul/Downloads/argon-dashboard-react-master/node_modules/react-dev-utils/noopServiceWorkerMiddleware.js:14:26)
    at Layer.handle [as handle_request] (/home/rahul/Downloads/argon-dashboard-react-master/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/rahul/Downloads/argon-dashboard-react-master/node_modules/express/lib/router/index.js:317:13)
    at /home/rahul/Downloads/argon-dashboard-react-master/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/rahul/Downloads/argon-dashboard-react-master/node_modules/express/lib/router/index.js:335:12)
    at next (/home/rahul/Downloads/argon-dashboard-react-master/node_modules/express/lib/router/index.js:275:10)
    at launchEditorMiddleware (/home/rahul/Downloads/argon-dashboard-react-master/node_modules/react-dev-utils/errorOverlayMiddleware.js:20:7)
    at Layer.handle [as handle_request] (/home/rahul/Downloads/argon-dashboard-react-master/node_modules/express/lib/router/layer.js:95:5)

**Comment by rarestoma** [comment]
Hi @porwal-rahul,

Thank you for working with our products.

Can you please give me more details? What commands did you run?

Thank you,
Rares

**Comment by radhikamehraa** [comment]
Hi I dint run any commands just tried linking it with my devpost but something seams to have changed on the app

**Comment by rarestoma** [comment]
Hi @radhikamehraa,

It seems like you are using the argon-dashboard-react product. Please open an issue to the official repo (https://github.com/creativetimofficial/argon-dashboard-react/issues) so our react team will see clearly what is happening.

Thank you,
Rares

**Comment by pabloEE7** [comment]
mismo problema, lo solucione editando  package.son "react-scripts": "3.3.1" a "react-scripts": "3.4.3" tendrían que arreglar eso desde el repo.
saludos
