### ISSUE TITLE
AssertionError [ERR_ASSERTION]: Task function must be specified

### ISSUE THREAD

**Issue by manghat** [creativetimofficial/argon-design-system#67]
assert.js:362
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/Users/manghat/Desktop/EI/GEC/code/argon-design-system-master/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/Users/manghat/Desktop/EI/GEC/code/argon-design-system-master/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/Users/manghat/Desktop/EI/GEC/code/argon-design-system-master/gulpfile.js:100:6)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at execute (/usr/local/lib/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js:36:18) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}

**Comment by rarestoma** [comment]
Hi,

Thank you for working with our products.

Can you please give us more details about your issue? Did you try modifying something?

Best,
Rares

**Comment by delyro** [comment]
I solved this issue by updating gulpfile.js:
https://gist.github.com/ntry/8a87ecb8427f044211dc3bfa390ff971#file-bootstrap-tutorial-gulp4-gulpfile-js

**Comment by shakhbozdanaboev2002** [comment]
generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
