### ISSUE TITLE
Fail when i try it to start

### ISSUE THREAD

**Issue by MrVapor01** [creativetimofficial/argon-design-system#89]
ERROR in ./src/assets/scss/argon.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/assets/scss/argon.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Cannot find module 'node-sass'
Require stack:
- C:\Users\Administrator\Desktop\MH_Development\mh-homepage\node_modules\sass-loader\lib\loader.js
- C:\Users\Administrator\Desktop\MH_Development\mh-homepage\node_modules\loader-runner\lib\loadLoader.js
- C:\Users\Administrator\Desktop\MH_Development\mh-homepage\node_modules\loader-runner\lib\LoaderRunner.js
- C:\Users\Administrator\Desktop\MH_Development\mh-homepage\node_modules\webpack\lib\NormalModule.js
- C:\Users\Administrator\Desktop\MH_Development\mh-homepage\node_modules\webpack\lib\NormalModuleFactory.js
- C:\Users\Administrator\Desktop\MH_Development\mh-homepage\node_modules\webpack\lib\Compiler.js
- C:\Users\Administrator\Desktop\MH_Development\mh-homepage\node_modules\webpack\lib\webpack.js
- C:\Users\Administrator\Desktop\MH_Development\mh-homepage\node_modules\@angular-devkit\build-webpack\src\webpack\index.js
- C:\Users\Administrator\Desktop\MH_Development\mh-homepage\node_modules\@angular-devkit\build-webpack\src\index.js
- C:\Users\Administrator\Desktop\MH_Development\mh-homepage\node_modules\@angular-devkit\build-angular\src\dev-server\index.js
- C:\Users\Administrator\Desktop\MH_Development\mh-homepage\node_modules\@angular-devkit\architect\src\architect-legacy.js
- C:\Users\Administrator\Desktop\MH_Development\mh-homepage\node_modules\@angular-devkit\architect\src\index.js
- C:\Users\Administrator\Desktop\MH_Development\mh-homepage\node_modules\@angular\cli\models\architect-command.js
- C:\Users\Administrator\Desktop\MH_Development\mh-homepage\node_modules\@angular\cli\commands\build-impl.js
- C:\Users\Administrator\Desktop\MH_Development\mh-homepage\node_modules\@angular-devkit\schematics\tools\export-ref.js
- C:\Users\Administrator\Desktop\MH_Development\mh-homepage\node_modules\@angular-devkit\schematics\tools\index.js
- C:\Users\Administrator\Desktop\MH_Development\mh-homepage\node_modules\@angular\cli\utilities\json-schema.js
- C:\Users\Administrator\Desktop\MH_Development\mh-homepage\node_modules\@angular\cli\models\command-runner.js
- C:\Users\Administrator\Desktop\MH_Development\mh-homepage\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\Administrator\Desktop\MH_Development\mh-homepage\node_modules\@angular\cli\lib\init.js
- C:\Users\Administrator\Desktop\MH_Development\mh-homepage\node_modules\@angular\cli\bin\ng
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.sassLoader (C:\Users\Administrator\Desktop\MH_Development\mh-homepage\node_modules\sass-loader\lib\loader.js:46:72)
i ｢wdm｣: Failed to compile.

**Comment by rarestoma** [comment]
Hi @MrVapor01,

Thank you for working with our products.

Are you using the angular version?

Thank you,
Rares

**Comment by MrVapor01** [comment]
Hello,

 

i have pull the angular version. He was on Angular 7 but he has not work. Then i have upgrade the Depends to Angular 8 and ist work fine. So i can make a PR on github then kann everyone use it on Angular 8. Because my Problem is solved.

 

Von: rarestoma <notifications@github.com> 
Gesendet: Montag, 27. Januar 2020 12:03
An: creativetimofficial/argon-design-system <argon-design-system@noreply.github.com>
Cc: _MrVapor <info@florianrichter.eu>; Mention <mention@noreply.github.com>
Betreff: Re: [creativetimofficial/argon-design-system] Fail when i try it to start (#89)

 

Hi @MrVapor01 <https://github.com/MrVapor01> ,

Thank you for working with our products.

Are you using the angular version?

Thank you,
Rares

**Comment by rarestoma** [comment]
Hi @MrVapor01,

Please open this issue on the official repo of Argon Design System Angular (https://github.com/creativetimofficial/argon-design-system-angular/issues).

Thank you,
Rares

**Comment by Rz-Rz** [comment]
Same error for me, after git cloning the repos, I launch npm install. It gives me an error related to sass. And yarn install also. Same error with node sass
